#!/usr/bin/env bash

# setup.sh
# Interactive self-host installer script for P2P File Share.
set -euo pipefail

# Style definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${BLUE}==================================================${NC}"
echo -e "${BLUE}   P2P File Share — Self-Host Setup Installer     ${NC}"
echo -e "${BLUE}==================================================${NC}"
echo ""

# 1. Dependency Checking
echo -e "Checking local environment dependencies..."

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "Error: '$1' is required but not installed."
    exit 1
  fi
}

check_cmd docker
check_cmd openssl

# Check docker compose compatibility
if docker compose version &>/dev/null; then
  COMPOSE_CMD="docker compose"
elif docker-compose version &>/dev/null; then
  COMPOSE_CMD="docker-compose"
else
  echo -e "Error: Docker Compose v2 is required but not installed."
  exit 1
fi

echo -e "Dependencies satisfied. Using: $COMPOSE_CMD"
echo ""

# 2. Interactive Input
read_input() {
  local prompt="$1"
  local var_name="$2"
  local default_val="${3:-}"
  local input_val
  
  if [ -n "$default_val" ]; then
    read -p "$(echo -e "$prompt [$default_val]: ")" input_val
    eval "$var_name=\"\${input_val:-$default_val}\""
  else
    read -p "$(echo -e "$prompt: ")" input_val
    while [ -z "$input_val" ]; do
      echo -e "This field is required."
      read -p "$(echo -e "$prompt: ")" input_val
    done
    eval "$var_name=\"\$input_val\""
  fi
}

read_confirm() {
  local prompt="$1"
  local var_name="$2"
  local default_choice="${3:-n}"
  local input_val
  
  read -p "$(echo -e "$prompt (y/N): ")" input_val
  input_val=$(echo "${input_val:-$default_choice}" | tr '[:upper:]' '[:lower:]')
  if [[ "$input_val" == "y" || "$input_val" == "yes" ]]; then
    eval "$var_name=1"
  else
    eval "$var_name=0"
  fi
}

# Collect required configurations
read_input "Enter your domain name (e.g. share.example.com)" SITE_DOMAIN
read_input "Enter your custom site branding name" SITE_NAME "P2P File Share"
read_input "Enter admin email address (for Let's Encrypt certificates)" ADMIN_EMAIL "admin@$SITE_DOMAIN"

# Collect optional services configurations
echo ""
echo -e "${BLUE}--- Optional Features Configuration ---${NC}"
read_confirm "Enable Anubis bot challenge filter (DDoS Protection)?" ENABLE_ANUBIS
read_confirm "Enable Plausible Analytics (requires clickhouse, adds 3 containers)?" ENABLE_PLAUSIBLE
read_confirm "Configure a local coturn TURN Relay server on ports 3478/5349?" ENABLE_TURN

# 3. Generate Secret Keys
echo ""
echo -e "Generating cryptographically secure secrets..."
POSTGRES_PASSWORD=$(openssl rand -hex 24)
ADMIN_JWT_SECRET=$(openssl rand -hex 32)
TURN_SECRET=$(openssl rand -hex 32)
echo "Secrets generated."

# 4. Write .env configuration file
echo -e "Writing config environmental variables into .env..."
cat << EOF > .env
# Configuration settings for P2P File Share self-host deployment
SITE_DOMAIN=${SITE_DOMAIN}
SITE_NAME=${SITE_NAME}
ADMIN_EMAIL=${ADMIN_EMAIL}

# Autogenerated Secrets
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
TURN_SECRET=${TURN_SECRET}
EOF

# Append optional configuration parameters based on selections
if [ "$ENABLE_TURN" -eq 1 ]; then
  cat << EOF >> .env
VITE_TURN_HOSTS=${SITE_DOMAIN}
VITE_TURN_PORT=3478
VITE_TURN_TLS_PORT=5349
VITE_TURN_REALM=${SITE_DOMAIN}
EOF
fi

# 5. Build Caddyfile Routing rules
echo -e "Building Caddyfile reverse proxy routing configurations..."
cp Caddyfile.template Caddyfile

# Replace markers in Caddyfile template
if [ "$ENABLE_ANUBIS" -eq 1 ]; then
  # Route traffic via Anubis PoW container
  sed -i 's/#ANUBIS_REPLACE_START/reverse_proxy anubis:8923/g' Caddyfile
  sed -i 's/reverse_proxy metadata-api:3001/# Routed to anubis/g' Caddyfile
  sed -i 's/#ANUBIS_REPLACE_END//g' Caddyfile
else
  # Route directly to Metadata API
  sed -i 's/#ANUBIS_REPLACE_START//g' Caddyfile
  sed -i 's/#ANUBIS_REPLACE_END//g' Caddyfile
fi

if [ "$ENABLE_PLAUSIBLE" -eq 1 ]; then
  # Route Plausible JS scripts
  PLAUSIBLE_ROUTE=$(cat << 'EOF'
    handle /js/script.js {
        reverse_proxy plausible:8000
    }
    handle /api/event {
        reverse_proxy plausible:8000
    }
EOF
)
  # Write mapping block
  sed -i "/#PLAUSIBLE_REPLACE_START/r /dev/stdin" Caddyfile <<< "$PLAUSIBLE_ROUTE"
fi

# 6. Execute Build and Deploy
echo ""
echo -e "Starting the P2P File Share Docker containers..."

# Build command with activated profiles
PROFILES=""
if [ "$ENABLE_ANUBIS" -eq 1 ]; then
  PROFILES="$PROFILES --profile anubis"
fi
if [ "$ENABLE_PLAUSIBLE" -eq 1 ]; then
  PROFILES="$PROFILES --profile plausible"
fi
if [ "$ENABLE_TURN" -eq 1 ]; then
  PROFILES="$PROFILES --profile turn"
fi

# Run the docker compose up build command
# shellcheck disable=SC2086
$COMPOSE_CMD -f docker-compose.selfhost.yml $PROFILES up -d --build

echo ""
echo -e "${GREEN}==================================================${NC}"
echo -e "${GREEN} P2P File Share Self-Hosting deployment complete! ${NC}"
echo -e "${GREEN}==================================================${NC}"
echo -e "Your instance is booting up at: ${BLUE}https://${SITE_DOMAIN}${NC}"
echo -e "Check container logs using: ${YELLOW}$COMPOSE_CMD -f docker-compose.selfhost.yml logs -f${NC}"
echo ""
